name: Build dylib

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Theos
        uses: theos/theos-action@main
        with:
          caching: true
          sdks-url: https://github.com/theos/sdks/releases/download/2024-11/iPhoneOS18.1.sdk.tar.xz

      - name: Build
        run: |
          export THEOS=~/theos
          export THEOS_MAKE_PATH=~/theos/makefiles
          make

      - name: Upload dylib
        uses: actions/upload-artifact@v3
        with:
          name: 80poolUnlimited.dylib
          path: .theos/obj/debug/80poolUnlimited.dylib
